Error in data.frame(gene_data, rbp_data, PUM1_data) : 
  arguments imply differing number of rows: 118, 119
Calls: corr_RBP_lncRNA -> data.frame
Execution halted
